# Generated by Django 2.1.5 on 2019-02-12 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valores_banco', '0002_auto_20190123_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='newsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('text', models.CharField(max_length=1000)),
                ('date', models.CharField(max_length=30)),
            ],
        ),
    ]
